data_path: "/"
output_path: "/"
checkpoint_last: "/"
random_seed: 32123
per_gpu_train_batch_size: 16
start_epoch: 0
gradient_accumulation_steps: 1
weight_decay: 0.1
learning_rate:
adam_epsilon:
warmup_steps:
num_training_steps:
fp16: 0
fp16_opt_level:
n_gpu: 1
max_grad_norm: 1
start_step: 0
logging_steps: 1